name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up virtual environment
        run: python -m venv venv
       
      - name: Activate virtual environment
        run: source venv/bin/activate  # For Windows: .\venv\Scripts\activate.bat

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      # You can add more steps like linting, security checks, etc., here.
